apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-service-b
  namespace: gitops-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-service-b
  template:
    metadata:
      labels:
        app: gitops-service-b
    spec:
      containers:
        - name: app
          image: Srinivasraop03/gitops-service-b:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-service-b
  namespace: gitops-service-b
spec:
  selector:
    app: gitops-service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
